### ISSUE TITLE
Request DataSet

### ISSUE THREAD

**Issue by yupotato** [haowang-cqu/TransTroj#1]
Hello,

I am a beginner in machine learning, currently learning and trying to reproduce your project. Could you please provide the dataset used in this project?

Thank you very much for your assistance.

Best regards！

**Comment by haowang02** [comment]
Hello, you can generate the data by running the following command:
```
python data_preparation.py  # You need to download the ImageNet dataset by yourself.
```

**Comment by haowang02** [comment]
You can download from [Baidu Netdisk](https://pan.baidu.com/s/16hxM33mgs3B0MvZMBRRolw?pwd=mhfp) (code: mhfp) and put all files in the data directory.

**Comment by yupotato** [comment]
thank you very much
