### ISSUE TITLE
请求预训练模型

### ISSUE THREAD

**Issue by yupotato** [haowang-cqu/TransTroj#2]
十分感谢您之前回复我的消息并提供给我数据集，帮助我在AI领域的学习进步。
       这里我还要冒昧打扰您一下。由于没有您实验的预训练模型，指导我实验的学长建议我使用simclr模型进行处理，但是由于我本身不是很精通这方面的内容，对于代码的修改可能不够完善，导致最后的实验结果不是很理想。所以在这里再次冒昧打扰您，希望请求您提供一下实验预训练的模型。
       我是上周开始学习深度学习的知识，所以本次复现实验对我难度有些大，同时在复现实验过程中有些疏漏，如果除了数据集、预训练模型外，还有其他我没有考虑到的数据，还恳请您能够一并提供给我。
       最后再次送上我的感谢，祝您科研顺利，生活顺心！

**Comment by haowang02** [comment]
预训练模型利用 torchvision 加载并保存即可。

**Comment by yupotato** [comment]
十分感谢您能够回复我的消息，我已经完成了您项目的复现，再次感谢您对我提供的帮助
